apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w01iw0ijz-python
  janus-idp.io/tekton: w01iw0ijz-python
  backstage.io/kubernetes-id: w01iw0ijz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w01iw0ijz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
